apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  techPreview:
    meshConfig:
      extensionProviders:
      - name: auth-provider
        envoyExtAuthzGrpc:
          service: authorino-authorino-authorization.auth-provider.svc.cluster.local
          port: 50051
  proxy:
    injection:
      # Setting it to false will enforce deployments need to have sidecar.istio.io/inject label set to "true"
      # There are deployments out of our control, such as Authorino's
      autoInject: true
    runtime:
      container:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 129Mi
  gateways:
    openshiftRoute:
      # To control the routes we create instead of letting IOR to create routes automatically for each and every Istio Gateway created
      enabled: false
  tracing:
    type: None
  addons:
    grafana:
      enabled: false
    kiali:
      name: kiali
      enabled: false
    prometheus:
      enabled: false
    jaeger:
      name: jaeger