apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
  namespace: talker-api
  labels:
    authorino/topic: talker-api
spec:
  hosts:
  - opendatahub.apps.$CLUSTER_DOMAIN

  identity:
  - name: kubernetes-users
    kubernetes:
      audiences:
      - https://kubernetes.default.svc

  authorization:
  - name: k8s-rbac
    kubernetes:
      user:
        valueFrom:
          authJSON: auth.identity.username
      resourceAttributes:
        namespace:
          value: talker-api
        group:
          value: talker-api
        resource:
          value: services
        verb:
          value: get

  response:
  - name: x-auth-data
    json:
      properties:
      - name: username
        valueFrom: { authJSON: auth.identity.username }
  
  denyWith:
    unauthenticated:      
      message:
        value: "Access denied"
    unauthorized:
      message:
        value: "Unauthorized :("