apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
  namespace: talker-api
  labels:
    authorino/topic: talker-api
spec:
  hosts:
  - talker-api.apps.$CLUSTER_DOMAIN

  identity:
  - name: kubernetes-users
    kubernetes:
      audiences:
      - https://kubernetes.default.svc

  authorization:
  - name: k8s-rbac
    when:
    - selector: auth.identity.extra.scopes\.authorization\.openshift\.io
      operator: excl
      value: role:talker-api-full:talker-api
    kubernetes:
      user:
        valueFrom:
          authJSON: auth.identity.sub
      resourceAttributes:
        namespace:
          value: talker-api
        group:
          value: talker-api
        resource:
          value: services
        verb:
          valueFrom:
            authJSON: context.request.http.method.@case:lower

  response:
  - name: x-forwarded-access-token
    plain:
      valueFrom:
        authJSON: context.request.http.headers.authorization.@extract:{"pos":1}

  denyWith:
    unauthenticated:
      code: 302
      headers:
      - name: Location
        valueFrom:
          authJSON: "${AUTH_ENDPOINT}?client_id=system%3Aserviceaccount%3Atalker-api%3Atalker-api-bff&redirect_uri=http%3A%2F%2Ftalker-api.apps.${CLUSTER_DOMAIN}%2Foauth%2Fcallback&response_type=code&scope=user%3Ainfo%20role%3Atalker-api-full%3Atalker-api&state={context.request.http.id}"
