apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: talker-api-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - opendatahub.apps.$CLUSTER_DOMAIN
    tls:
      mode: SIMPLE
      credentialName: opendatahub-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: talker-api
  namespace: istio-system
  labels:
    app: talker-api
spec:
  hosts:
  - opendatahub.apps.$CLUSTER_DOMAIN
  gateways:
  - talker-api-gw
  http:
  - route:
    - destination:
        host: talker-api.talker-api.svc.cluster.local
        port:
          number: 80
