# ServiceAccount to be used as OAuth client for the API
# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/authentication_and_authorization/using-service-accounts-as-oauth-client
apiVersion: v1
kind: ServiceAccount
metadata:
  name: talker-api-bff
  namespace: talker-api
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.first: "http://talker-api.apps.$CLUSTER_DOMAIN/oauth/callback"
